name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{toJSON(github.event)}}"      
#      - run: echo ${{ github.event.head_commit.message }}
#      - run: systemctl --user restart web
#      - run: systemctl --user status web
